### ISSUE TITLE
Support for configuration as code

### ISSUE THREAD

**Issue by rnkhouse** [jenkinsci/xray-connector-plugin#20]
Xray Configuration should be configured from Jenkins configuration as code plugin (https://www.jenkins.io/projects/jcasc/).

**Comment by Russell616** [comment]
Hi,

Thank you for using the Xray connector plugin.

Can you tell me the error/problem that you are facing when using "configuration as code"?

**Comment by rnkhouse** [comment]
@Russell616 I haven't tried it as I didn't find documentation to setup Xray setting from configuration as code.

**Comment by Russell616** [comment]
Hi @rnkhouse 

I created [an issue](https://jira.xpand-it.com/browse/XRAYJENKINS-93) in our Backlog to look into it.
If you want, you may create an account in our Jira and follow the issue to be notified on any future updates.

Thank you again for your suggestion :)
