### ISSUE TITLE
Log the http status code of the connection test

### ISSUE THREAD

**Issue by joerg1985** [jenkinsci/xray-connector-plugin#56]
The current log message of the connection test does not show the status code of the connection test.
This makes it hard to find the real issue, like is it authentication, firewall configuration, etc.

e.g. a current log line
``
Dec 17, 2021 9:15:29 AM SEVERE com.xpandit.plugins.xrayjenkins.model.ServerConfiguration jiraServerTestConnection
URL provided is not from a Jira instance -> https://.../rest/api/2/serverInfo didn't return a valid result.
``

Adding the http status code to the log line could help finding the real issue

e.g. a log line pointing to an authentication issue 
``
Dec 17, 2021 9:15:29 AM SEVERE com.xpandit.plugins.xrayjenkins.model.ServerConfiguration jiraServerTestConnection
URL provided is not from a Jira instance -> https://.../rest/api/2/serverInfo didn't return a valid result, http status code 401.
``

e.g. a log line pointing to an firewall issue 
``
Dec 17, 2021 9:15:29 AM SEVERE com.xpandit.plugins.xrayjenkins.model.ServerConfiguration jiraServerTestConnection
URL provided is not from a Jira instance -> https://.../rest/api/2/serverInfo didn't return a valid result, http status code 403.
``

**Comment by Russell616** [comment]
Hi everyone!

I just wanted to let you know that we just release Xray-connector 2.6.0 with this issue is implemented.
