### ISSUE TITLE
label for relative path of feature file is not correct after importing a feature file to Jira project.

### ISSUE THREAD

**Issue by jinlxz** [jenkinsci/xray-connector-plugin#61]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.319.1
OS: Linux - 4.15.0-45-generic
---
Office-365-Connector:4.15.2
ace-editor:1.1
active-directory:2.25
ant:1.12
antisamy-markup-formatter:2.4
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
authorize-project:1.4.0
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.1-1
bouncycastle-api:2.25
branch-api:2.7.0
build-timeout:1.20
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-folder:6.16
command-launcher:1.6
credentials:2.6.1
credentials-binding:1.27
cucumber-living-documentation:3.2
cucumber-reports:5.6.1
cucumber-trends-report:1.3
display-url-api:2.3.5
docker-commons:1.17
docker-java-api:3.1.5.2
docker-plugin:1.2.3
docker-slaves:1.0.7
docker-workflow:1.26
durable-task:1.39
echarts-api:5.2.1-2
email-ext:2.84
external-monitor-job:1.7
font-awesome-api:5.15.4-1
generic-webhook-trigger:1.77
git:4.9.0
git-client:3.10.0
git-server:1.10
github-api:1.133
gitlab-plugin:1.5.22
gradle:1.37.1
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
jackson2-api:2.13.0-230.v59243c64b0a5
javadoc:1.6
jaxb:2.3.0
jdk-tool:1.5
jjwt-api:0.11.2-9.c8b45b8bb173
jquery:1.12.4-1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
kubernetes:1.30.5
kubernetes-client-api:5.4.1
kubernetes-credentials:0.9.0
ldap:2.7
lockable-resources:2.12
mailer:1.34
matrix-auth:2.6.8
matrix-project:1.19
maven-plugin:3.16
mercurial:2.15
metrics:4.0.2.8
momentjs:1.1.1
okhttp-api:3.14.9
pam-auth:1.6
pipeline-build-step:2.15
pipeline-graph-analysis:1.11
pipeline-input-step:2.12
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.2
pipeline-model-definition:1.9.2
pipeline-model-extensions:1.9.2
pipeline-rest-api:2.19
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.9.2
pipeline-stage-view:2.19
plain-credentials:1.7
plugin-util-api:2.5.0
popper-api:1.16.1-2
popper2-api:2.10.2-1
rebuild:1.32
resource-disposer:0.16
role-strategy:3.2.0
scm-api:2.6.5
script-security:1.78
snakeyaml-api:1.29.1
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
structs:1.23
timestamper:1.13
token-macro:267.vcdaea6462991
trilead-api:1.0.13
variant:1.4
windows-slaves:1.8
workflow-aggregator:2.6
workflow-api:2.47
workflow-basic-steps:2.24
workflow-cps:2.94
workflow-cps-global-lib:2.21
workflow-durable-task-step:2.40
workflow-job:2.42
workflow-multibranch:2.26
workflow-scm-step:2.13
workflow-step-api:2.24
workflow-support:3.8
ws-cleanup:0.39
xray-connector:2.5.3
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller OS: Ubuntu 18.04.4 LTS
agent OS: Ubuntu 18.04.6 LTS

### Reproduction steps

1. set up a jenkins job and configure the job to import a feature file to a Jira project

### Expected Results

Test issues should be created in the Jira project, and each issue should have a label whose value is the relative path of the feature file under Jenkins job workspace.

### Actual Results

the issues are created, but the label for relative path of the feature file has incorrect value, the value begins with the job name, the job name should not be included in the relative path of the feature file.

![image](https://user-images.githubusercontent.com/9611732/149281436-9dfe47ba-9056-4145-adb6-3a6cd1d6fa37.png)

the label for the relative path of the feature file is used to recognize the existing Jira issues when importing feature files, thus the job name should not be included in the label value as the job name may be changed.

### Anything else?

I modified the code and commented the code for deleting the feature zip file, deployed to jenkins and ran the job, then downloaded the zip file, found that it indeed contains the job name as its top folder.

**Comment by Russell616** [comment]
Hi everyone!

I just wanted to let you know that we just release Xray-connector 2.6.0 with this issue is fixed.
